server:
  port: 8082
  
spring:
  application:
    name: inventory-service
          
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 1
    
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
    
feign:
  hystrix:
    enabled: false